stages:
  - build
  - deploy

.build_template: &build_definition
  stage: build


x64_dbg:
  <<: *build_definition
  image: lv2plugin/debian-x64
  script:
    - meson . build -Dbuildtype=debug -Dwarning_level=3 -Dwerror=true -Dtest=true -Db_coverage=true
    - ninja -C build test
    - ninja -C build coverage-html
  artifacts:
    paths:
      - build/meson-logs/coveragereport

x64_rel:
  <<: *build_definition
  image: lv2plugin/debian-x64
  script:
    - meson . build -Dbuildtype=release -Dwarning_level=3 -Dwerror=true -Dtest=true
    - ninja -C build test


mac_dbg:
  <<: *build_definition
  tags: [macos]
  script:
    - meson . build -Dbuildtype=debug -Dwarning_level=3 -Dwerror=true -Dtest=true
    - ninja -C build test

mac_rel:
  <<: *build_definition
  tags: [macos]
  script:
    - meson . build -Dbuildtype=release -Dwarning_level=3 -Dwerror=true -Dtest=true
    - ninja -C build test


win_dbg:
  <<: *build_definition
  tags: [windows,meson]
  script:
    - meson . build -Dbuildtype=debug -Dwarning_level=3 -Dwerror=true -Dtest=true
    - ninja -C build test

win_rel:
  <<: *build_definition
  tags: [windows,meson]
  script:
    - meson . build -Dbuildtype=release -Dwarning_level=3 -Dwerror=true -Dtest=true
    - ninja -C build test


pages:
  stage: deploy
  script:
    - mkdir -p .public
    - mv build/meson-logs/coveragereport/ .public/coverage
    - mv .public public
  dependencies:
    - x64_dbg
  artifacts:
    paths:
      - public
  only:
    - master
