# Copyright 2021-2022 David Robillard <d@drobilla.net>
# SPDX-License-Identifier: 0BSD OR GPL-3.0-only

default:
  image: lv2plugin/debian-x64
  script:
    - meson setup build -Dwerror=true
    - ninja -C build test

dev:
  image: lv2plugin/debian-x64
  script:
    - meson setup build -Dbuildtype=debug -Dstrict=true -Dwerror=true -Db_coverage=true
    - ninja -C build test
    - ninja -C build coverage-html
    - meson configure -Dbuildtype=release -Db_coverage=false build
    - ninja -C build test
  coverage: '/ *lines\.*: \d+\.\d+.*/'
  artifacts:
    paths:
      - build/meson-logs/coveragereport

static:
  image: lv2plugin/debian-x64
  script:
    - meson setup build -Ddefault_library=static -Dstrict=true -Dwerror=true
    - ninja -C build test

sanitize:
  image: lv2plugin/debian-x64-clang
  script:
    - meson setup build -Db_lundef=false -Dbuildtype=plain -Dstrict=true -Dwerror=true -Dcpp_args="-fno-sanitize-recover=all -fsanitize=address -fsanitize=undefined -fsanitize=float-divide-by-zero -fsanitize=implicit-conversion -fsanitize=local-bounds -fsanitize=nullability" -Dcpp_link_args="-fno-sanitize-recover=all -fsanitize=address -fsanitize=undefined -fsanitize=float-divide-by-zero -fsanitize=implicit-conversion -fsanitize=local-bounds -fsanitize=nullability"
    - ninja -C build test
    - meson configure build -Dbuildtype=debugoptimized -Dcpp_args="" -Dcpp_link_args=""
    - meson configure build -Db_sanitize=thread
    - ninja -C build test
  variables:
    CXX: "clang++"

# Linux Distributions

fedora:
  image: lv2plugin/fedora-dev
  script:
    - meson setup build -Dbuildtype=plain -Dstrict=true -Dwerror=true
    - ninja -C build test
  variables:
    CFLAGS: -O2 -D_FORTIFY_SOURCE=2

# Linux Platforms

arm64:
  image: lv2plugin/debian-arm64
  script:
    - meson setup build --cross-file=/usr/share/meson/cross/aarch64-linux-gnu.ini -Dbuildtype=debug -Dstrict=true -Dwerror=true
    - ninja -C build test
    - meson configure -Dbuildtype=release build
    - ninja -C build test

mingw64:
  image: lv2plugin/debian-mingw64
  script:
    - meson setup build --cross-file=/usr/share/meson/cross/x86_64-w64-mingw32.ini -Dcpp_args="-static-libgcc" -Dcpp_link_args="-static-libgcc" -Dbuildtype=debug -Dstrict=true -Dwerror=true
    - ninja -C build test
    - meson configure -Dbuildtype=release build
    - ninja -C build test
  variables:
    WINEPATH: "Z:\\usr\\lib\\gcc\\x86_64-w64-mingw32\\10-win32;Z:\\builds\\drobilla\\exess\\build"

# Non-Linux/Docker rows (not hosted)

freebsd:
  tags: [freebsd,meson]
  script:
    - meson setup build -Dbuildtype=debug -Dstrict=true -Dwerror=true
    - ninja -C build test
    - meson configure -Dbuildtype=release build
    - ninja -C build test

mac:
  tags: [macos]
  script:
    - meson setup build -Dbuildtype=debug -Dstrict=true -Dwerror=true
    - ninja -C build test
    - meson configure -Dbuildtype=release build
    - ninja -C build test

win:
  tags: [windows,meson]
  script:
    - meson setup build -Dbuildtype=debug -Dstrict=true -Dwerror=true
    - ninja -C build test
    - meson configure -Dbuildtype=release build
    - ninja -C build test

# Coverage

pages:
  stage: deploy
  script:
    - mkdir -p .public
    - mv build/meson-logs/coveragereport/ .public/coverage
    - mv .public public
  needs:
    - dev
  artifacts:
    paths:
      - public
  only:
    - main
